color00="{{ colors.black|format_sh }}"
color08="{{ colors.bblack|format_sh }}"
color01="{{ colors.red|format_sh }}"
color09="{{ colors.bred|format_sh }}"
color02="{{ colors.green|format_sh }}"
color10="{{ colors.bgreen|format_sh }}"
color03="{{ colors.yellow|format_sh }}"
color11="{{ colors.byellow|format_sh }}"
color04="{{ colors.blue|format_sh }}"
color12="{{ colors.bblue|format_sh }}"
color05="{{ colors.magenta|format_sh }}"
color13="{{ colors.bmagenta|format_sh }}"
color06="{{ colors.cyan|format_sh }}"
color14="{{ colors.bcyan|format_sh }}"
color07="{{ colors.white|format_sh }}"
color15="{{ colors.bwhite|format_sh }}"
color_foreground="{{ colors.foreground|format_sh }}"
color_background="{{ colors.background|format_sh }}"
color_cursor="99/99/99"
color16=$color_foreground
color17=$color_background
color18="44/44/44" # darker than black
color19="6e/6b/5e" # Base 02
color20="99/95/80" # Base 04
color21="e8/e4/cf" # Base 06
